Repository ResidenciaTICBrisa/T2G8-Plugin-Wordpress, pull requests merged in 2024-08, with the labels that each got.

#201 Adição da página index na landing page
  docs/css/style.css
  docs/images/bg1.png
  docs/images/representacaomapa.png
  docs/index.html
Labels: documentation, DEV

#209 Mecanismos de sinalizacao de tabela selecionada
  lgbtq_connect/includes/admin/admin_script.js
  lgbtq_connect/includes/admin/pagina_administracao.php
  lgbtq_connect/includes/admin/style-admin.css
Labels: enhancement

#211 Feat: Adicao do bloco do plugin no editor de blocos do wordpress
  lgbtq_connect/assets/js/block.js
  lgbtq_connect/assets/styles/block_style.css
  lgbtq_connect/index.php
Labels: enhancement, DEV

#214 Desinstalação do LGBTQ+ Connect
  lgbtq_connect.zip
  lgbtq_connect/uninstall.php
Labels: enhancement, DEV

#215 Adição de paginação para a tabela de formulários
  lgbtq_connect.zip
  lgbtq_connect/includes/admin/admin_script.js
  lgbtq_connect/includes/admin/pagina_administracao.php
  lgbtq_connect/includes/admin/realizar-query.php
  lgbtq_connect/includes/admin/style-admin.css
  lgbtq_connect/index.php
  package.json
  tests/js/filtro_admin.test.js
  tests/js/ordenacao_admin.test.js
  tests/js/tabela_admin.test.js
Labels: enhancement

#217 Refactor: Alterando nomes do BD em ingles para portugues
  lgbtq_connect/includes/admin/admin_script.js
  lgbtq_connect/includes/admin/formulario-admin-page.php
  lgbtq_connect/includes/data/conexao_bd.php
  lgbtq_connect/includes/data/process_form.php
  lgbtq_connect/preenche_bd.php
  tests/php/AlteraStatusTest.php
Labels: bug, DEV

#216 Filtro por tipo de serviço mapa
  lgbtq_connect/assets/index.html
  lgbtq_connect/assets/js/script.js
  lgbtq_connect/assets/styles/styles.css
Labels: enhancement

#221 Adição de alertas visuais nos campos do formulário
  lgbtq_connect/assets/index.html
  lgbtq_connect/assets/js/formulario.js
  lgbtq_connect/assets/js/funcionalidades.js
  lgbtq_connect/assets/js/script.js
  lgbtq_connect/assets/styles/styles.css
Labels: enhancement

#223 Landingpage
  docs/Atas/ata-reuniao1.md
  docs/Atas/ata-reuniao2.md
  docs/Atas/ata-reuniao3.md
  docs/Atas/ata-reuniao4.md
  docs/Atas/ata-reuniao5.md
  docs/assets_Antigo/images/Arquitetura_col.drawio.html
  docs/assets_Antigo/images/logo.png
  docs/assets_Antigo/stylesheets/extra.css
  docs/contato.html
  docs/css/bootstrap.css
  docs/css/font-awesome.min.css
  docs/css/responsive.css
  docs/css/style.css
  docs/css/style.css.map
  docs/css/style.scss
  docs/download.html
  docs/fonts/fontawesome-webfont.ttf
  docs/fonts/fontawesome-webfont.woff
  docs/fonts/fontawesome-webfont.woff2
  docs/images/Marker_Padrao.png
  docs/images/bg1.png
  docs/images/brisalogo.png
  docs/images/logo.png
  docs/images/representacaomapa.png
  docs/images/tutorial_instalacao/tela1-tutorial_intalacao.png
  docs/images/tutorial_instalacao/tela2-tutorial_intalacao.png
  docs/images/tutorial_instalacao/tela3-tutorial_intalacao.png
  docs/images/tutorial_instalacao/tela4-tutorial_intalacao.png
  docs/images/tutorial_instalacao/tela5-tutorial_intalacao.png
  docs/images/tutorial_instalacao/tela6-tutorial_intalacao.png
  docs/images/tutorial_instalacao/tela7-tutorial_intalacao.png
  docs/images/tutorial_uso/tela1-tutorialuso.png
  docs/images/tutorial_uso/tela10-tutorialuso.png
  docs/images/tutorial_uso/tela11-tutorialuso.png
  docs/images/tutorial_uso/tela11.1-tutorialuso.png
  docs/images/tutorial_uso/tela12-tutorialuso.png
  docs/images/tutorial_uso/tela13-tutorialuso.png
  docs/images/tutorial_uso/tela14-tutorialuso.png
  docs/images/tutorial_uso/tela2-tutorialuso.png
  docs/images/tutorial_uso/tela3-tutorialuso.png
  docs/images/tutorial_uso/tela4-tutorialuso.png
  docs/images/tutorial_uso/tela5-tutorialuso.png
  docs/images/tutorial_uso/tela6-tutorialuso.png
  docs/images/tutorial_uso/tela6.1-tutorialuso.png
  docs/images/tutorial_uso/tela6.2-tutorialuso.png
  docs/images/tutorial_uso/tela7-tutorialuso.png
  docs/images/tutorial_uso/tela8-tutorialuso.png
  docs/images/tutorial_uso/tela9-tutorialuso.png
  docs/images/tutorial_uso/tela9.1-tutorialuso.png
  docs/index.html
  docs/js/bootstrap.js
  docs/js/custom.js
  docs/js/jquery-3.4.1.min.js
  docs/preparandoambiente.md
  docs/tutorial.html
  docs/tutorial.md
Labels: documentation, DEV
